spring:
  application:
    name: spring-netty
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  mvc:
    static-path-pattern: /static/**
    throw-exception-if-no-handler-found: true
  resources:
    static-locations: classpath:/static/

  freemarker:
    suffix: .ftl
    content-type: text/html
    charset: UTF-8
    cache: false
    allow-request-override: false #是否允许HttpServletRequest属性覆盖(隐藏)控制器生成的同名模型属性
    allow-session-override: false #是否允许HttpSession属性覆盖(隐藏)控制器生成的同名模型属性
    check-template-location: false #是否检查模板位置是否存在
    expose-spring-macro-helpers: false #设定是否以springMacroRequestContext的形式暴露RequestContext给Spring’s macro library使用
    expose-session-attributes: false #是否在merge模板的时候，将HttpSession属性都添加到model中
    expose-request-attributes: false #设定所有request的属性在merge到模板的时候，是否要都添加到model中
    template-loader-path: classpath:/templates/
    settings:
      template_update_delay: 0
      default_encoding: UTF-8
      classic_compatible: true
      datetime_format: yyyy-MM-dd HH:mm:ss
      date_format: yyyy-MM-dd
      time_format: HH:mm:ss
      number_format: 0.#
      template_exception_handler: ignore

system:
  netty:
    port: ${NETTY_PORT:9081}
    path: ${NETTY_PATH:/ws}
